---
name: Tests

on:
  pull_request:
  push: { branches: [ "main" ] } # Just because I'm being naughty and pushing directly to main

jobs:
  tests:
    name: Run go tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with: { go-version: "^1.21" }
    - run: go test -v ./test/...
